package uni.miskolc.ips.ilona.measurement.model.position;


import java.util.UUID;

/**
 * Represent a part of a building. Rooms shall be represented by Zone objects.
 * 
 * @author zsolt
 *
 */
public class Zone {

	public static final Zone UNKNOWN_POSITION;
	static {
		UNKNOWN_POSITION = new Zone("Unknown");
		UNKNOWN_POSITION.setId(new UUID(0, 0));
	}

	/**
	 * It is the identifier of the zone. It is generated by the system.
	 */
	private UUID id;
	private String name;

	public Zone() {

	}

	public Zone(String name) {
		super();
		this.id = UUID.randomUUID();
		this.name = name;
	}

	public void addInternalZone(Zone internal) {
		if (internal == null) {
			return;
		}
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Zone == false) {
			return false;
		}
		return this.id.equals(((Zone) obj).id);
	}

	@Override
	public String toString() {
		return "Zone [id=" + id + ", name=" + name + "]";
	}

}
